"""add device token_hash

Revision ID: 025111b41382
Revises: 86f9a651b606
Create Date: 2026-05-13 17:43:38.328776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025111b41382'
down_revision: Union[str, Sequence[str], None] = '86f9a651b606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('token_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_devices_token_hash'), 'devices', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_token_hash'), table_name='devices')
    op.drop_column('devices', 'token_hash')
    # ### end Alembic commands ###
