"""add car body_type, fuel_type, transmission, engine_size

Revision ID: 0db48da12991
Revises: ddb88ce0d21a
Create Date: 2026-05-12 21:46:58.754796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db48da12991'
down_revision: Union[str, Sequence[str], None] = 'ddb88ce0d21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('body_type', sa.String(), server_default='Car', nullable=False))
    op.add_column('cars', sa.Column('fuel_type', sa.String(), server_default='Petrol', nullable=False))
    op.add_column('cars', sa.Column('transmission', sa.String(), server_default='Automatic', nullable=False))
    op.add_column('cars', sa.Column('engine_size', sa.Integer(), server_default='2000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'engine_size')
    op.drop_column('cars', 'transmission')
    op.drop_column('cars', 'fuel_type')
    op.drop_column('cars', 'body_type')
    # ### end Alembic commands ###
