"""initial schema

Revision ID: 7b0bfa075d87
Revises: 
Create Date: 2026-03-24 12:14:40.070829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0bfa075d87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_car_id'), 'devices', ['car_id'], unique=False)
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_devices_car_id'), table_name='devices')
    # ### end Alembic commands ###
