"""add car brake_condition, owner_type

Revision ID: 86f9a651b606
Revises: 0db48da12991
Create Date: 2026-05-13 14:20:07.363740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f9a651b606'
down_revision: Union[str, Sequence[str], None] = '0db48da12991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('brake_condition', sa.String(), server_default='Good', nullable=False))
    op.add_column('cars', sa.Column('owner_type', sa.String(), server_default='First', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'owner_type')
    op.drop_column('cars', 'brake_condition')
    # ### end Alembic commands ###
