"""telemetry: add speed and engine_load

Revision ID: af2d17c56788
Revises: 401ca60eef58
Create Date: 2026-05-08 16:03:07.789015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2d17c56788'
down_revision: Union[str, Sequence[str], None] = '401ca60eef58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_logs', sa.Column('speed', sa.Float(), nullable=True))
    op.add_column('telemetry_logs', sa.Column('engine_load', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_logs', 'engine_load')
    op.drop_column('telemetry_logs', 'speed')
    # ### end Alembic commands ###
