"""alert add resolved_at and composite index

Revision ID: ddb88ce0d21a
Revises: af2d17c56788
Create Date: 2026-05-12 09:00:27.355097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb88ce0d21a'
down_revision: Union[str, Sequence[str], None] = 'af2d17c56788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_alerts_car_type_resolved', 'alerts', ['car_id', 'type', 'resolved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_car_type_resolved', table_name='alerts')
    op.drop_column('alerts', 'resolved_at')
    # ### end Alembic commands ###
